# Generated by Django 6.0.7 on 2026-07-12 03:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('name_model', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('max_load_capacity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('odometer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('acquisition_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('On Trip', 'On Trip'), ('In Shop', 'In Shop'), ('Retired', 'Retired')], default='Available', max_length=20)),
                ('region', models.CharField(blank=True, max_length=60, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vehicles_vehicle',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='vehicles_ve_status_f71f77_idx'), models.Index(fields=['type'], name='vehicles_ve_type_7478a7_idx'), models.Index(fields=['registration_number'], name='vehicles_ve_registr_3774f3_idx')],
            },
        ),
    ]
