# Generated by Django 6.0.7 on 2026-07-12 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('license_number', models.CharField(max_length=40, unique=True)),
                ('license_category', models.CharField(max_length=20)),
                ('license_expiry', models.DateField()),
                ('contact_number', models.CharField(max_length=20)),
                ('safety_score', models.DecimalField(decimal_places=1, default=100, max_digits=4)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('On Trip', 'On Trip'), ('Off Duty', 'Off Duty'), ('Suspended', 'Suspended')], default='Available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'drivers_driver',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='drivers_dri_status_d7a5f5_idx'), models.Index(fields=['license_expiry'], name='drivers_dri_license_3e242f_idx')],
            },
        ),
    ]
